### ISSUE TITLE
Removal from Chrome Web Store

### ISSUE THREAD

**Issue by cglong** [Rob--W/stackexchange-notifications#31]
This extension seems to have been removed from the Chrome Web Store. When I try to open [the extension in the Store](https://chrome.google.com/webstore/detail/ijglncoabcgieiokjmgdogpefdblmnle), I get a `404 Not Found`. This leads to Chrome saying:

> This extension violates the Chrome Web Store policy.

I assume this isn't true, but it'd be good to confirm and get the extension added back if possible.

**Comment by Rob--W** [comment]
It was taken down for the lack of privacy policy, and despite repeated attempts since July it's still down. Here is what has been going on:

- CWS: E-mail with warning about non-compliance due to the lack of privacy policy.
- Me: Added explicit section called "Privacy policy" that describes what the extension does (despite it already being listed in the item description...)
- CWS: Rejected with generic complaints that the privacy policy is incomplete.
- Me: Multiple attempts to rephrase the text, followed by rejection.
- CWS: Two weeks after the warning, the item got removed because of non-compliance.
- Me: Reach out to developer support to ask for clarification about the rejection reason.
- CWS: "Violation: The provided privacy policy link (https://robwu.nl/privacy/) does not talk about user data collection."
- Me: "This link was at my profile, not on the specific webstore item. I have removed the link from my profile since it confused you and I explicitly listed the relevant privacy policies in the item descriptions of the Chrome Web Store anyway."
- CWS: "Upon a subsequent review, we found your extension with id:”ijglncoabcgieiokjmgdogpefdblmnle” and name: ”Desktop Notifications for Stack Exchange” is compliant with all our policies. Unfortunately, we cannot approve a submission that has been rejected. Hence, we request you to re-submit your extension on the developer dashboard. Your submission will be approved if we find it to be compliant with all our policies."
- Me: Resubmitted since they claimed that the extension would be approved if I were to resubmit.
- CWS: Rejected again.

Since then I have tried to tweak the listing. My latest attempt to fix this is to create a new page that aggregates the existing privacy policies of my extensions at https://robwu.nl/privacy/cws/ and link it from my profile. I hope that it will be accepted eventually.

If you'd like, you could also try Firefox. The extension there is still available, and the add-on gallery there is more user- and developer-friendly: https://addons.mozilla.org/en-US/firefox/addon/real-time-desktop-notificat/

**Comment by cglong** [comment]
Thanks for the detailed explanation; I've never published an extension before, so it was really insightful to see just how opaque the process can be 😅 Closing as the extension seems to be republished and stable (for now 🙂).
